import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryProvider } from "@/provider/query-provider";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/AuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth/authOptions";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = getServerSession(authOptions)

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <Toaster />
          <AuthProvider session={session}>

          {children}
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
